gradle -b netsharp-core/build.gradle uploadArchives
gradle -b netsharp-basebiz/build.gradle uploadArchives
gradle -b netsharp-basebiz-web/build.gradle uploadArchives
gradle -b netsharp-cache-base/build.gradle uploadArchives
gradle -b netsharp-cache-plugin/build.gradle uploadArchives
gradle -b netsharp-cache-service/build.gradle uploadArchives
gradle -b netsharp-communication/build.gradle uploadArchives
gradle -b netsharp-panda/build.gradle uploadArchives
gradle -b netsharp-persistence/build.gradle uploadArchives
gradle -b netsharp-scrum/build.gradle uploadArchives
gradle -b netsharp-weixin/build.gradle uploadArchives
gradle -b weixin-sdk-mp/build.gradle uploadArchives
gradle -b weixin-sdk-ep/build.gradle uploadArchives
gradle -b weixin-sdk-tp/build.gradle uploadArchives
#gradle -b netsharp-rest/build.gradle uploadArchives